services:
  bookstack:
    image: lscr.io/linuxserver/bookstack             #Pulling Image , Best practice is to use specific versions
    container_name: bookstack  
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://bookstack.example.com   # Make sure to resolve this URL to DNS name or hostname of the server donot use Ipaddress , if ip address changes it will break all the images in the wiki.
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=<yourdbpass>         # use variables  .env file 
      - DB_DATABASE=bookstackapp
    volumes:
      - ./bookstack_app_data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=<yourdbpass>     #use variables .env file
      - TZ=Europe/London
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=<yourdbpass>
    volumes:
      - ./bookstack_db_data:/config
    restart: unless-stopped
